/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import veranum.DAO.DAORol;
import veranum.GUI.cliente.MainCliente;
import veranum.GUI.empresas.MainEmpresas;
import veranum.GUI.habitaciones.MainHabitaciones;
import veranum.GUI.hotel.MainHotel;
import veranum.GUI.insumos.MainInsumos;
import veranum.GUI.localizador.MainLocalizador;
import veranum.GUI.log.MainLog;
import veranum.GUI.reportes.MainReportes;
import veranum.GUI.reservas.MainReserva;
import veranum.GUI.reservasA.MainReservasA;
import veranum.GUI.servicios.MainServicios;
import veranum.GUI.usuarios.MainUsuarios;
import veranum.entities.ClPasajeros;
import veranum.entities.ClRol;


/**
 *
 * @author veranum
 */
public class AdminVeranum extends javax.swing.JFrame {
    public ClPasajeros usuario;
    
    /**
     * Creates new form AdminVeranum
     * @param pasajero
     */
    public AdminVeranum(ClPasajeros pasajero) {
        initComponents();
        this.usuario = pasajero;
        lblBienvenido.setText("Bienvenido "+usuario.getNombre());
        DAORol drol = new DAORol();
        ClRol rol = drol.sqlLeer(usuario.getIdRol());
        this.setTitle(rol.getNombre().toString());
    }
    
     public AdminVeranum() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        btnHoteles = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        btnLocalizador = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        btnReservas = new javax.swing.JButton();
        btnHabitaciones = new javax.swing.JButton();
        btnCambiarUsuario = new javax.swing.JButton();
        btnReservasA = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnEmpresas = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador | Veranum");
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(102, 153, 255));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/logo.jpg"))); // NOI18N

        btnHoteles.setBackground(new java.awt.Color(255, 255, 255));
        btnHoteles.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnHoteles.setText("Hoteles");
        btnHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelesActionPerformed(evt);
            }
        });

        btnServicios.setBackground(new java.awt.Color(255, 255, 255));
        btnServicios.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnInsumos.setBackground(new java.awt.Color(255, 255, 255));
        btnInsumos.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnInsumos.setText("Insumos");
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });

        btnLocalizador.setBackground(new java.awt.Color(255, 255, 255));
        btnLocalizador.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnLocalizador.setText("Administrador Regiones");
        btnLocalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizadorActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblBienvenido.setText("Bienvenido ");

        btnReservas.setBackground(new java.awt.Color(255, 255, 255));
        btnReservas.setText("Reservar");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        btnHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnHabitaciones.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnHabitaciones.setText("Habitaciones");
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });

        btnCambiarUsuario.setBackground(new java.awt.Color(102, 255, 102));
        btnCambiarUsuario.setText("Cambiar Usuario");
        btnCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarUsuarioActionPerformed(evt);
            }
        });

        btnReservasA.setBackground(new java.awt.Color(255, 255, 255));
        btnReservasA.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnReservasA.setText("Reservas");
        btnReservasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasAActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(204, 204, 255));
        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpresas.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        btnEmpresas.setText("Empresas");
        btnEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnInsumos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHabitaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(btnHoteles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLocalizador)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservasA, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(lblBienvenido))
                        .addGroup(panelMenuLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnCambiarUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenido)
                .addGap(33, 33, 33)
                .addComponent(btnHoteles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHabitaciones)
                .addGap(8, 8, 8)
                .addComponent(btnServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocalizador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservasA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpresas)
                .addGap(18, 18, 18)
                .addComponent(btnReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnCambiarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(7, 7, 7))
        );

        panelContenido.setBackground(new java.awt.Color(102, 153, 255));
        panelContenido.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelesActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainHotel(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHotelesActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainServicios(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainUsuarios(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainCliente(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainInsumos(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnLocalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizadorActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainLocalizador(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLocalizadorActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainReportes(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
       try {
            new helper.IFrameHelper().openContenidoAdmin(new MainReserva(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainHabitaciones(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarUsuarioActionPerformed
        MainVeranum ver = new MainVeranum();
        ver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCambiarUsuarioActionPerformed

    private void btnReservasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasAActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainReservasA(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReservasAActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainLog(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasActionPerformed
        try {
            new helper.IFrameHelper().openContenidoAdmin(new MainEmpresas(), panelContenido);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminVeranum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEmpresasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVeranum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarUsuario;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpresas;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnHoteles;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnLocalizador;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnReservasA;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
