/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI;

import helper.Formularios;
import javax.swing.JOptionPane;
import veranum.DAO.DAOLogin;
import veranum.DAO.DAORol;
import veranum.entities.ClPasajeros;
import veranum.entities.ClRol;

/**
 *
 * @author veranum
 */
public class MainVeranum extends javax.swing.JFrame {
    public static ClPasajeros p;
    /**
     * Creates new form MainVeranum
     */
    public MainVeranum() {
        initComponents();
        this.getRootPane().setDefaultButton(btnIngresar);
        this.setTitle("Bienvenidos a Veranum");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRut = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        imgLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login | Veranum Hotel");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 153, 255));
        setForeground(java.awt.Color.lightGray);
        setIconImages(null);
        setName("frMain"); // NOI18N
        setResizable(false);

        lbRut.setText("Rut:");

        lbContrasena.setText("Contraseña: ");

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/logo.jpg"))); // NOI18N

        lbTitulo.setBackground(new java.awt.Color(102, 153, 255));
        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Control de Gestion Administrativo");

        btnIngresar.setBackground(new java.awt.Color(51, 153, 255));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRut)
                            .addComponent(lbContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut)
                            .addComponent(txtContrasena)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(imgLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLogo)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIngresar.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        DAOLogin u =  new DAOLogin();
        if(!Formularios.validarRut(txtRut.getText())){
            JOptionPane.showMessageDialog(this, "Rut Incorrecto."); 
            return;
        }
        p = new ClPasajeros(txtRut.getText(), txtContrasena.getText());
        
        if(u.LoginIn(p) == null){
           JOptionPane.showMessageDialog(this, "Combinación Usuario/Contraseña incorrecto."); 
           return;  
        }else{
            DAORol drol = new DAORol();
            ClRol rol = drol.sqlLeer(p.getIdRol());
            if(rol.getNombre().equals("Admin")){
                AdminVeranum ver = new AdminVeranum(p);
                ver.setExtendedState(ver.MAXIMIZED_BOTH);
                ver.setVisible(true);
                this.setVisible(false);
                
            } else if(rol.getNombre().equals("Encargado Hotel")){
                EncargadoHoteleriaVeranum ver = new EncargadoHoteleriaVeranum(p);
                ver.setExtendedState(ver.MAXIMIZED_BOTH);
                ver.setVisible(true);
                this.setVisible(false);
            } else if(rol.getNombre().equals("Encargado Cocina")){
                EncargadoCocinaVeranum ver = new EncargadoCocinaVeranum(p);
                ver.setExtendedState(ver.MAXIMIZED_BOTH);
                ver.setVisible(true);
                this.setVisible(false);
            } else if(rol.getNombre().equals("Encargado Servicios")){
                EncargadoServicioVeranum ver = new EncargadoServicioVeranum(p);
                ver.setExtendedState(ver.MAXIMIZED_BOTH);
                ver.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "No tienes los permisos suficientes."); 
            return;
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        Formularios.validarRutLargo(evt);
        if (!(txtRut.getText().length() < 9)) {
            Formularios.limpiarTxt(txtRut);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        } 
    }//GEN-LAST:event_txtRutKeyTyped

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        if (!(txtContrasena.getText().length() < 30)) {
            Formularios.limpiarTxt(txtContrasena);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado"); 
        } 
    }//GEN-LAST:event_txtContrasenaKeyTyped


    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainVeranum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainVeranum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbRut;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
