/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.servicios;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;


/**
 *
 * @author veranum
 */
public class MainServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainServicios
     */
    public MainServicios() {
        initComponents();
        tabContServicios.addTab("Servicios", new panelServicios());
        tabContServicios.addTab("Tipo Características", new panelTipoCaract());
        tabContServicios.addTab("Características", new panelCaracteristicas());
        tabContServicios.addChangeListener(new ChangeListener() { 
            @Override
            public void stateChanged(ChangeEvent e) {
                switch (tabContServicios.getSelectedIndex()) {
                    case 0:
                        tabContServicios.setComponentAt(0, new panelServicios());
                        break;
                    case 1:
                        tabContServicios.setComponentAt(1, new panelTipoCaract());
                        break;
                    case 2:
                        tabContServicios.setComponentAt(2, new panelCaracteristicas());
                        break;
                    default:
                        break;
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContServicios = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContServicios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContServicios)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContServicios;
    // End of variables declaration//GEN-END:variables
}
