/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.habitaciones;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author veranum
 */
public class MainHabitaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainHabitaciones
     */
    public MainHabitaciones() {
        initComponents();
        tabContenido.addTab("Habitaciones", new panelHabitaciones());
        tabContenido.addTab("Tipo Habitación", new panelTipoHab());
        tabContenido.addTab("Estado Habitación", new panelEstadoHab());
        tabContenido.addTab("Características Habitación", new panelHabCaract());
        tabContenido.addTab("Historial de precios", new panelHistorial());
        
        tabContenido.addChangeListener(new ChangeListener() { 
            @Override
            public void stateChanged(ChangeEvent e) {
                switch (tabContenido.getSelectedIndex()) {
                    case 0:
                        tabContenido.setComponentAt(0, new panelHabitaciones());
                        break;
                    case 1:
                        tabContenido.setComponentAt(1, new panelTipoHab());
                        break;
                    case 2:
                        tabContenido.setComponentAt(2, new panelEstadoHab());
                        break;
                    case 3:
                        tabContenido.setComponentAt(3, new panelHabCaract());
                        break;
                    case 4:
                        tabContenido.setComponentAt(4, new panelHistorial());
                        break;
                    default:
                        break;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenido = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContenido;
    // End of variables declaration//GEN-END:variables
}
