/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.habitaciones;


import java.io.FileOutputStream;
import java.io.IOException;
 
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import veranum.DAO.DAOHistorialPrecios;
import veranum.DAO.DAOHoteles;
import veranum.entities.ClHistorialPrecios;
import veranum.entities.ClHoteles;

/**
 *
 * @author veranum
 */
public class panelHistorial extends javax.swing.JPanel {
    private DefaultTableModel dt = new DefaultTableModel();
    JFileChooser fc;
    /**
     * Creates new form panelHistorial
     */
    public panelHistorial() {
        initComponents();
        this.leerTodos(false);
        this.cargarHotel();
        fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        grDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        grDatos.getTableHeader().setReorderingAllowed(false);
        grDatos.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grDatos = new javax.swing.JTable();
        btnReporte = new javax.swing.JButton();
        cbHotel = new javax.swing.JComboBox();
        lblHoteles = new javax.swing.JLabel();
        btnFiltro = new javax.swing.JButton();

        grDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Hotel", "Habitación", "Precio Antiguo", "Precio Nuevo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grDatos);

        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        lblHoteles.setText("Hotel:");

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHoteles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporte)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporte)
                    .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoteles)
                    .addComponent(btnFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        this.leerTodos(true);
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        ArrayList<ClHistorialPrecios> datos = DAOHistorialPrecios.sqlLeerTodos();
        fc.showOpenDialog(this);
        String path = fc.getSelectedFile().getAbsolutePath();
        try {
            writeExcel(datos, path + "\\reporteHabitacionesHistorial.xls");
        } catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error desconocido. Intente de nuevo");
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    public void writeExcel(ArrayList<ClHistorialPrecios> datos, String excelFilePath) throws IOException {
        Workbook workbook = new HSSFWorkbook();
        Sheet sheet = workbook.createSheet();

        int rowCount = 0;

        Row row = sheet.createRow(++rowCount);
        writeReporteHead(row);
        
        for (ClHistorialPrecios aBook : datos) {
            row = sheet.createRow(++rowCount);
            writeReporte(aBook, row);
        }

        try (FileOutputStream outputStream = new FileOutputStream(excelFilePath)) {
            workbook.write(outputStream);
            JOptionPane.showMessageDialog(this, "Generado con éxito");
        }
    }
    private void writeReporteHead(Row row) {
        Cell cell = row.createCell(1);
        cell.setCellValue("Hotel");

        cell = row.createCell(2);
        cell.setCellValue("Habitación");

        cell = row.createCell(3);
        cell.setCellValue("Precio");
        
        cell = row.createCell(4);
        cell.setCellValue("Nuevo Precio");
        
    }
    
    private void writeReporte(ClHistorialPrecios historial, Row row) {
        Cell cell = row.createCell(1);
        cell.setCellValue(historial.getHotel());

        cell = row.createCell(2);
        cell.setCellValue(historial.getUbicacion());

        cell = row.createCell(3);
        cell.setCellValue(historial.getPrecio());
        
        cell = row.createCell(4);
        cell.setCellValue(historial.getNuevo_precio());
    }
    
     private void leerTodos(boolean filtro){
        ArrayList dato;
        if(!filtro)
            dato = DAOHistorialPrecios.sqlLeerTodos();
        else
            dato = DAOHistorialPrecios.sqlByHotel(((ClHoteles)cbHotel.getSelectedItem()).getIdHotel());
        
        dt =  (DefaultTableModel) grDatos.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }     
        for(int x=0; x < dato.size(); x++){
            ClHistorialPrecios xx = (ClHistorialPrecios)dato.get(x);
            Object[] fila = new Object[6];
            fila[0] = xx.getIdHistorialPrecios();
            fila[1] = xx.getHotel();
            fila[2] = xx.getUbicacion();
            fila[3] = xx.getPrecio();
            fila[4] = xx.getNuevo_precio();
            fila[5] = xx.getFecha();
            dt.addRow(fila);
        }
    }
     
     private void cargarHotel(){
        for (Object dato : DAOHoteles.sqlLeerTodos()) {
            cbHotel.addItem(dato);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cbHotel;
    private javax.swing.JTable grDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoteles;
    // End of variables declaration//GEN-END:variables
}
