/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reservas;

/**
 *
 * @author veranum
 */
public class MainReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainReserva
     */
    public MainReserva() {
        initComponents();
        tabReservas.addTab("Usuarios", new PasoUno_Usuarios(tabReservas));
        tabReservas.addTab("Reservas", new PasoUno_Usuarios(tabReservas));
        tabReservas.addTab("Servicios", new PasoUno_Usuarios(tabReservas));
        tabReservas.addTab("Finalizar", new PasoUno_Usuarios(tabReservas));
        tabReservas.setEnabledAt(1, false);
        tabReservas.setEnabledAt(2, false);
        tabReservas.setEnabledAt(3, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabReservas = new javax.swing.JTabbedPane();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(tabReservas);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabReservas;
    // End of variables declaration//GEN-END:variables
}
