/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reservas;

import helper.Formularios;
import java.util.ArrayList;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOEstadoReserva;
import veranum.DAO.DAOHotelServicio;
import veranum.DAO.DAOServicios;
import veranum.DAO.DAOTipoHab;
import veranum.entities.ClEstadoReserva;
import veranum.entities.ClHabitaciones;
import veranum.entities.ClHotelServicios;
import veranum.entities.ClReservar;
import veranum.entities.ClServicios;
import veranum.entities.ClTipoHabitacion;

/**
 *
 * @author veranum
 */
public class PasoTres_Servicios extends javax.swing.JPanel {
    private final JTabbedPane myTab;
    private final ClReservar reserva;
    private DefaultTableModel dt = new DefaultTableModel();
    private int id_hotel = 0;
    private int total_servicios = 0;
    /**
     * Creates new form PasoTres_Servicios
     * @param t
     * @param reserva
     */
    public PasoTres_Servicios(JTabbedPane t, ClReservar reserva) {
        initComponents();
        this.myTab = t;
        this.reserva = reserva;
        lblResumenRut.setText("Rut: "+reserva.getUsuario().getRut());
        lblResumenNombre.setText("Nombre: "+reserva.getUsuario().getNombre()+" "+reserva.getUsuario().getApellido_pa()+" "+reserva.getUsuario().getApellido_ma());
        lblResumenDias.setText("Días: "+reserva.getDias());
        lblResumenFechaIngreso.setText("Ingreso: "+Formularios.deFechaToString(reserva.getFechaIngreso()));
        lblResumenFechaSalida.setText("Salida: "+Formularios.deFechaToString(reserva.getFechaSalida()));
        lblResumenTotal.setText("Total: $"+reserva.getTotal());
        lblResumenTotalxNoche.setText("Total x Noche: $"+reserva.getTotalxnoche());
        lblResumenTotalHabitaciones.setText("Habitaciones: "+reserva.getReservas().size());
        this.cargarHabitacionesReservadas();
        this.cargarServiciosHoteles();
        this.cargarEstados();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblResumen = new javax.swing.JLabel();
        lblResumenRut = new javax.swing.JLabel();
        lblResumenNombre = new javax.swing.JLabel();
        lblResumenFechaIngreso = new javax.swing.JLabel();
        lblResumenFechaSalida = new javax.swing.JLabel();
        lblResumenDias = new javax.swing.JLabel();
        lblResumenTotalHabitaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grResumen = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        grServiciosContratados = new javax.swing.JTable();
        lblResumenTotalHabitaciones1 = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        lblServicios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grServicios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblResumenTotalxNoche = new javax.swing.JLabel();
        lblResumenTotal = new javax.swing.JLabel();
        lblEstadoReserva = new javax.swing.JLabel();
        cbEstadoReserva = new javax.swing.JComboBox();

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setText("Reserva de Servicios");

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/atras.png"))); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblResumen.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblResumen.setText("RESUMEN DEL MOMENTO:");

        lblResumenRut.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenRut.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenRut.setText("Rut");

        lblResumenNombre.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenNombre.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenNombre.setText("NombreCompleto");

        lblResumenFechaIngreso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenFechaIngreso.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenFechaIngreso.setText("Fecha Ingreso");

        lblResumenFechaSalida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenFechaSalida.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenFechaSalida.setText("FechaSalida");

        lblResumenDias.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenDias.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenDias.setText("Dias");

        lblResumenTotalHabitaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenTotalHabitaciones.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenTotalHabitaciones.setText("Habitaciones Cant");

        grResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitación", "Tipo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grResumen);

        grServiciosContratados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servicio", "Precio", "#"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grServiciosContratados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grServiciosContratadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grServiciosContratados);

        lblResumenTotalHabitaciones1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenTotalHabitaciones1.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenTotalHabitaciones1.setText("Servicios Contratados:");

        btnReservar.setBackground(new java.awt.Color(51, 255, 51));
        btnReservar.setText("RESERVAR");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResumenTotalHabitaciones1)
                            .addComponent(lblResumenTotalHabitaciones)
                            .addComponent(lblResumenDias)
                            .addComponent(lblResumenFechaSalida)
                            .addComponent(lblResumenFechaIngreso)
                            .addComponent(lblResumenNombre)
                            .addComponent(lblResumenRut)
                            .addComponent(lblResumen))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenFechaIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenFechaSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenTotalHabitaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResumenTotalHabitaciones1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblServicios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblServicios.setText("Servicios:");

        grServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Servicio", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grServiciosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(grServicios);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblResumenTotalxNoche.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenTotalxNoche.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenTotalxNoche.setText("TotalxNoche");

        lblResumenTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblResumenTotal.setForeground(new java.awt.Color(87, 87, 87));
        lblResumenTotal.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumenTotalxNoche)
                    .addComponent(lblResumenTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblResumenTotalxNoche)
                .addGap(18, 18, 18)
                .addComponent(lblResumenTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEstadoReserva.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lblEstadoReserva.setText("Estado Reserva:");

        cbEstadoReserva.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addComponent(btnAtras)
                    .addComponent(lblServicios)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstadoReserva)
                    .addComponent(cbEstadoReserva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(64, 64, 64)
                        .addComponent(lblServicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadoReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        myTab.setEnabledAt(2, false);
        myTab.setSelectedIndex(1);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void grServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grServiciosMouseClicked
        int row_dos = Formularios.getTablaSeleccionada(evt, grServicios, 2);

        if(row_dos >= 0){
            this.reserva.getServicios().add(this.leerServicio(Integer.parseInt(grServicios.getValueAt(row_dos, 0).toString())));
            this.cargarServiciosReservados();
        }
    }//GEN-LAST:event_grServiciosMouseClicked

    private void grServiciosContratadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grServiciosContratadosMouseClicked
        int row_dos = Formularios.getTablaSeleccionada(evt, grServiciosContratados, 2);

        if(row_dos >= 0){
            this.reserva.getServicios().remove(Integer.parseInt(grServiciosContratados.getValueAt(row_dos, 2).toString()));
            this.cargarServiciosReservados();
        }
    }//GEN-LAST:event_grServiciosContratadosMouseClicked

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        reserva.setEstado((ClEstadoReserva)cbEstadoReserva.getSelectedItem());
        long newTotal = reserva.getTotal() + total_servicios;
        reserva.setTotal(newTotal);
        
        myTab.setEnabledAt(3, true);
        myTab.setComponentAt(3, new PasoCuatro_Finalizar(myTab, reserva));
        myTab.setSelectedIndex(3);
    }//GEN-LAST:event_btnReservarActionPerformed

    private void cargarHabitacionesReservadas(){
        dt =  (DefaultTableModel) grResumen.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }  
        for(int x=0; x < this.reserva.getReservas().size(); x++){
            ClHabitaciones xx = (ClHabitaciones)this.reserva.getReservas().get(x);
            this.id_hotel = xx.getIdHotel();
            Object[] fila = new Object[4];
            fila[0] = xx.getUbicacion();
            fila[1] = ((ClTipoHabitacion)DAOTipoHab.sqlLeer(xx.getIdHabitacionTipo())).getNombre();
            fila[2] = xx.getPrecio();
            dt.addRow(fila);
        }    
    }
    
    private void cargarServiciosReservados(){
        dt =  (DefaultTableModel) grServiciosContratados.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }  
        total_servicios = 0;
        for(int x=0; x < this.reserva.getServicios().size(); x++){
            ClServicios xx = (ClServicios)this.reserva.getServicios().get(x);
            Object[] fila = new Object[4];
            total_servicios += xx.getPrecio();
            fila[0] = xx.getNombre();
            fila[1] = xx.getPrecio();
            fila[2] = x;
            dt.addRow(fila);
        }   
        calculaPrecio();
    }
    
    private long calculaPrecio(){
        long precio = reserva.getTotal() + total_servicios;
        lblResumenTotal.setText("Total: $"+precio);
        return precio;
    }
    
    private ClServicios leerServicio(int id){
        return DAOServicios.sqlLeer(id);
    }
    
    
    private void cargarServiciosHoteles(){
         ArrayList sev = new ArrayList<>();
        dt =  (DefaultTableModel) grServicios.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }  
        sev = DAOHotelServicio.sqlLeerXHotel(id_hotel);
        
        for(int x=0; x < sev.size(); x++){
            ClHotelServicios xx = (ClHotelServicios)sev.get(x);
            Object[] fila = new Object[3];
            fila[0] = xx.getIdServicio();
            fila[1] = xx.getNombreServicio();
            fila[2] = xx.getPrecioServicio();
            dt.addRow(fila);
        }    
    }
    
    private void cargarEstados(){
        for (Object dato : DAOEstadoReserva.sqlLeerTodos()) {
            cbEstadoReserva.addItem(dato);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox cbEstadoReserva;
    private javax.swing.JTable grResumen;
    private javax.swing.JTable grServicios;
    private javax.swing.JTable grServiciosContratados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEstadoReserva;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblResumenDias;
    private javax.swing.JLabel lblResumenFechaIngreso;
    private javax.swing.JLabel lblResumenFechaSalida;
    private javax.swing.JLabel lblResumenNombre;
    private javax.swing.JLabel lblResumenRut;
    private javax.swing.JLabel lblResumenTotal;
    private javax.swing.JLabel lblResumenTotalHabitaciones;
    private javax.swing.JLabel lblResumenTotalHabitaciones1;
    private javax.swing.JLabel lblResumenTotalxNoche;
    private javax.swing.JLabel lblServicios;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
