/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.insumos;

import helper.Formularios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import veranum.DAO.DAOProveedores;
import veranum.DAO.DAORol;
import veranum.entities.ClPasajeros;
import veranum.entities.ClRol;

/**
 *
 * @author veranum
 */
public class panelProvee extends javax.swing.JPanel {

    private boolean paraGrabar = false;
    private DefaultTableModel dt = new DefaultTableModel();
    private int id = 0;
    /**
     * Creates new form panelProvee
     */
    public panelProvee() {
        initComponents();
        grUsuario.setEnabled(true);
        grUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        grUsuario.getTableHeader().setReorderingAllowed(false);
        Formularios.DesactiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
        btDesactivarEditarUsuarios.setVisible(false);
        this.leerTodos(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRut = new javax.swing.JLabel();
        lbNombreUsuario = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        txtRutUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtMailUsuario = new javax.swing.JTextField();
        txtDireccionUsuario = new javax.swing.JTextField();
        btGrabarUsuarios = new javax.swing.JButton();
        btEliminarUsuario = new javax.swing.JButton();
        btEditarUsuario = new javax.swing.JButton();
        txtBuscarUsuario = new javax.swing.JTextField();
        btBuscarUsuario = new javax.swing.JButton();
        btBuscarTodosUsuario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grUsuario = new javax.swing.JTable();
        btDesactivarEditarUsuarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        lbRut.setText("Rut:");

        lbNombreUsuario.setText("Nombre:");

        lbTelefono.setText("Telefono:");

        lbMail.setText("E-mail:");

        lbDireccion.setText("Direccion:");

        txtRutUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutUsuarioKeyTyped(evt);
            }
        });

        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtMailUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMailUsuarioKeyTyped(evt);
            }
        });

        txtDireccionUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionUsuarioKeyTyped(evt);
            }
        });

        btGrabarUsuarios.setText("Grabar");
        btGrabarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrabarUsuariosActionPerformed(evt);
            }
        });

        btEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/delete96.png"))); // NOI18N
        btEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarUsuarioActionPerformed(evt);
            }
        });

        btEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/write13.png"))); // NOI18N
        btEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarUsuarioActionPerformed(evt);
            }
        });

        txtBuscarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarUsuarioKeyTyped(evt);
            }
        });

        btBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/magnifier12.png"))); // NOI18N
        btBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarUsuarioActionPerformed(evt);
            }
        });

        btBuscarTodosUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/veranum/imagenes/refresh_16.png"))); // NOI18N
        btBuscarTodosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosUsuarioActionPerformed(evt);
            }
        });

        grUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Rut", "Nombre", "Teléfono", "E-Mail", "Dirección", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grUsuario);

        btDesactivarEditarUsuarios.setBackground(new java.awt.Color(255, 0, 0));
        btDesactivarEditarUsuarios.setText("Salir Modo Editar");
        btDesactivarEditarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesactivarEditarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarTodosUsuario))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addComponent(btGrabarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRut)
                            .addComponent(lbNombreUsuario)
                            .addComponent(lbTelefono))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDesactivarEditarUsuarios)
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDireccion)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarUsuario)
                    .addComponent(btBuscarTodosUsuario)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEliminarUsuario)
                        .addComponent(btEditarUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRut)
                    .addComponent(txtRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDesactivarEditarUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMail)
                    .addComponent(txtMailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGrabarUsuarios)
                .addContainerGap(355, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutUsuarioKeyTyped
        Formularios.validarRutLargo(evt);
        if (!(txtRutUsuario.getText().length() < 11)) {
            Formularios.limpiarTxt(txtRutUsuario);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtRutUsuarioKeyTyped

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        if (!(txtNombreUsuario.getText().length() < 15)) {
            Formularios.limpiarTxt(txtNombreUsuario);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        Formularios.soloNumeros(evt);
        if (!(txtTelefono.getText().length() < 15)) {
            Formularios.limpiarTxt(txtTelefono);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtMailUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMailUsuarioKeyTyped
        if (!(txtMailUsuario.getText().length() < 20)) {
            Formularios.limpiarTxt(txtMailUsuario);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtMailUsuarioKeyTyped

    private void txtDireccionUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionUsuarioKeyTyped
        if (!(txtDireccionUsuario.getText().length() < 50)) {
            Formularios.limpiarTxt(txtDireccionUsuario);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtDireccionUsuarioKeyTyped

    private void btGrabarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrabarUsuariosActionPerformed
        if(!Formularios.validarRut(txtRutUsuario.getText())){
            JOptionPane.showMessageDialog(this, "Rut Incorrecto.");
            Formularios.limpiarTxt(txtRutUsuario);
            return;
        }
        if(!paraGrabar){
            if(txtRutUsuario.getText().equals("")
                || txtNombreUsuario.getText().equals("")
                || txtTelefono.getText().equals("")
                || txtMailUsuario.getText().equals("")
                || txtDireccionUsuario.getText().equals("")
            ){
                JOptionPane.showMessageDialog(this, "Ingrese los Datos");
            }else{
                try {
                    if(DAOProveedores.sqlLeer(txtRutUsuario.getText().toUpperCase()) == null){
                        DAOProveedores.sqlInsert(new ClPasajeros(txtRutUsuario.getText()
                            , txtNombreUsuario.getText()
                            , txtTelefono.getText()
                            , txtMailUsuario.getText()
                            , txtDireccionUsuario.getText()
                            , 5)
                    );
                    JOptionPane.showMessageDialog(this, "Agregado");
                    Formularios.DesactiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
                    Formularios.limpiar(this);
                    this.leerTodos(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Rut ya existe");
                    Formularios.limpiarTxt(txtRutUsuario);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al insertar el dato.");
            }
        }
        }else{
            try {
                DAOProveedores.sqlUpdate(new ClPasajeros(  this.id
                    , txtRutUsuario.getText()
                    , txtNombreUsuario.getText()
                    , txtTelefono.getText()
                    , txtMailUsuario.getText()
                    , txtDireccionUsuario.getText()
                    , 5
                ));
                JOptionPane.showMessageDialog(this, "Modificado");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al modificar el dato.");
            }
            Formularios.DesactiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
            Formularios.limpiar(this);
            this.leerTodos(true);
            this.paraGrabar = false;
            this.btnEditarMode();
        }
    }//GEN-LAST:event_btGrabarUsuariosActionPerformed

    private void btEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarUsuarioActionPerformed
        this.leerUsuarios(Formularios.getSelectedRow(grUsuario));
        if(this.id == 0){
            JOptionPane.showMessageDialog(this, "NO existe para eliminar");
        }else{
            try {
                DAOProveedores.sqlDelete(new ClPasajeros(this.id));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No se ha podido eliminar.");
            }
            JOptionPane.showMessageDialog(this, "Eliminado");
            helper.Formularios.limpiar(this);
            Formularios.DesactiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
            this.leerTodos(true);
        }
    }//GEN-LAST:event_btEliminarUsuarioActionPerformed

    private void btEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarUsuarioActionPerformed
        this.leerUsuarios(Formularios.getSelectedRow(grUsuario));
        this.paraGrabar = true;
        this.btnEditarMode();
    }//GEN-LAST:event_btEditarUsuarioActionPerformed

    private void txtBuscarUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuarioKeyTyped
        if (!(txtBuscarUsuario.getText().length() < 15)) {
            Formularios.limpiarTxt(txtBuscarUsuario);
            JOptionPane.showMessageDialog(this, "Máximo de caracteres alcanzado");
        }
    }//GEN-LAST:event_txtBuscarUsuarioKeyTyped

    private void btBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarUsuarioActionPerformed
        if(txtBuscarUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese datos para buscar [Búsqueda por RUT]");
        }else{
            this.leerTodos(false);
        }
    }//GEN-LAST:event_btBuscarUsuarioActionPerformed

    private void btBuscarTodosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosUsuarioActionPerformed
        this.leerTodos(true);
    }//GEN-LAST:event_btBuscarTodosUsuarioActionPerformed

    private void grUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grUsuarioMouseClicked
        int row_dos = Formularios.getTablaSeleccionada(evt, grUsuario, 2);
        if(row_dos >= 0){
            this.leerUsuarios(Integer.parseInt(grUsuario.getValueAt(row_dos, 0).toString()));
            Formularios.ActiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
            this.paraGrabar = true;
            this.btnEditarMode();
        } else {
            Formularios.ActiveBotonesEliminarEditar(btEditarUsuario, btEliminarUsuario);
        }
    }//GEN-LAST:event_grUsuarioMouseClicked

    private void btDesactivarEditarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesactivarEditarUsuariosActionPerformed
        this.paraGrabar = false;
        this.btnEditarMode();
    }//GEN-LAST:event_btDesactivarEditarUsuariosActionPerformed

    
    private void leerUsuarios(int id){
        this.id = id;
        ClPasajeros usu = DAOProveedores.sqlLeer(id);
        txtRutUsuario.setText(usu.getRut());
        txtNombreUsuario.setText(usu.getNombre());
        txtTelefono.setText(usu.getTelefono());
        txtMailUsuario.setText(usu.getEmail());
        txtDireccionUsuario.setText(usu.getDireccion());
        txtTelefono.setText(usu.getTelefono());
        
    }
    
    private void leerTodos(boolean todos){
        ArrayList usu;
        if(todos)
            usu = DAOProveedores.sqlLeerTodos();
        else 
            usu = DAOProveedores.sqlBuscarByNombre(txtBuscarUsuario.getText());
        
        dt =  (DefaultTableModel) grUsuario.getModel();        
        for (int i = dt.getRowCount() -1; i >= 0; i--){  
            dt.removeRow(i);
        }        
        for(int x=0; x < usu.size(); x++){
            ClPasajeros xx = (ClPasajeros)usu.get(x);
            Object[] fila = new Object[11];
            fila[0] = xx.getIdPasajero();
            fila[1] = xx.getRut();
            fila[2] = xx.getNombre(); 
            fila[3] = xx.getTelefono();
            fila[4] = xx.getEmail();
            fila[5] = xx.getDireccion();
            fila[6] = ((ClRol)DAORol.sqlLeer(xx.getIdRol())).getNombre();
            dt.addRow(fila);
        }
    }
    
    
    private void btnEditarMode(){
        if(!this.paraGrabar){
            btDesactivarEditarUsuarios.setVisible(false);
            helper.Formularios.limpiar(this);
        } else {
            btDesactivarEditarUsuarios.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarTodosUsuario;
    private javax.swing.JButton btBuscarUsuario;
    private javax.swing.JButton btDesactivarEditarUsuarios;
    private javax.swing.JButton btEditarUsuario;
    private javax.swing.JButton btEliminarUsuario;
    private javax.swing.JButton btGrabarUsuarios;
    private javax.swing.JTable grUsuario;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbRut;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTextField txtBuscarUsuario;
    private javax.swing.JTextField txtDireccionUsuario;
    private javax.swing.JTextField txtMailUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRutUsuario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
