/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reportes;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author veranum
 */
public class MainReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainReportes
     */
    public MainReportes() {
        initComponents();
        tabContenidoReportes.addTab("Reportes", new panelReportes());
        tabContenidoReportes.addTab("Inspecciones Sanitarias", new panelInspecciones());
        tabContenidoReportes.addTab("Tipo Reportes", new panelTipoRep());
        tabContenidoReportes.addChangeListener(new ChangeListener() { 
            @Override
            public void stateChanged(ChangeEvent e) {
                switch (tabContenidoReportes.getSelectedIndex()) {
                    case 0:
                        tabContenidoReportes.setComponentAt(0, new panelReportes());
                        break;
                    case 1:
                        tabContenidoReportes.setComponentAt(1, new panelInspecciones());
                        break;
                    case 2:
                        tabContenidoReportes.setComponentAt(2, new panelTipoRep());
                        break;
                    default:
                        break;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabContenidoReportes = new javax.swing.JTabbedPane();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoReportes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContenidoReportes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTabbedPane tabContenidoReportes;
    // End of variables declaration//GEN-END:variables
}
