/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veranum.GUI.reservasA;

/**
 *
 * @author veranum
 */
public class MainReservasA extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainReservasA
     */
    public MainReservasA() {
        initComponents();
        tabContenidos.add("Consultar", new panelConsulta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenidos = new javax.swing.JTabbedPane();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(tabContenidos);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContenidos;
    // End of variables declaration//GEN-END:variables
}
